### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group' when using remote gif URL

### ISSUE THREAD

**Issue by rutherford** [google/gif-for-cli#18]
I had the same issue detailed in issue 7 and on deleting the directory specified got the following regex exception instead:

> $ gif-for-cli 10988977
> 
> Traceback (most recent call last):
>   File "/home/me/envs/terminal/bin/gif-for-cli", line 11, in <module>
>     sys.exit(main())
>   File "/home/me/envs/terminal/lib/python3.6/site-packages/gif_for_cli/__main__.py", line 105, in main
>     execute(os.environ, sys.argv[1:], sys.stdout)
>   File "/home/me/envs/terminal/lib/python3.6/site-packages/gif_for_cli/__main__.py", line 72, in execute
>     cpu_pool_size=args.cpu_pool_size,
>   File "/home/me/envs/terminal/lib/python3.6/site-packages/gif_for_cli/generate/__init__.py", line 170, in generate
>     num_frames, seconds = _run_ffmpeg(**options)
>   File "/home/me/envs/terminal/lib/python3.6/site-packages/gif_for_cli/generate/__init__.py", line 73, in _run_ffmpeg
>     num_frames = int(re.search(r'frame=\s*(\d+)', err).group(1))
> AttributeError: 'NoneType' object has no attribute 'group'

python3.6 on debian 8.0

**Comment by rutherford** [comment]
Should point out, works fine on local gifs.

**Comment by SeanHayes** [comment]
That means something went wrong with ffmpeg, and it's not giving the output we expect.

What version of ffmpeg are you using?

**Comment by rutherford** [comment]
Yes you're right, it was only affecting HTTPS connections. Adding `--enable-openssl` when configuring FFMPEG fixed.

```
$ ffmpeg -version
ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
built with gcc 4.9.2 (Debian 4.9.2-10+deb8u1)
configuration: --enable-gpl --enable-postproc --enable-swscale --enable-avfilter --enable-libmp3lame
libavutil      54. 27.100 / 54. 27.100
libavcodec     56. 41.100 / 56. 41.100
libavformat    56. 36.100 / 56. 36.100
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 16.101 /  5. 16.101
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.100 /  1.  2.100
libpostproc    53.  3.100 / 53.  3.100
```

**Comment by SeanHayes** [comment]
I'll reopen this, gif-for-cli should handle this error better and try to warn the user ffmpeg needs to be reconfigured.
