### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Abhinickz** [google/gif-for-cli#19]
Some GIFs giving this below error:

```
[16:28:43 abhasker@wsl -> ~$ gif 12122337
Processed 15/15 frames...
Traceback (most recent call last):
  File "/home/abhasker/.local/bin/gif-for-cli", line 11, in <module>
    sys.exit(main())
  File "/home/abhasker/.local/lib/python3.5/site-packages/gif_for_cli/__main__.py", line 89, in main
    execute(os.environ, sys.argv[1:], sys.stdout)
  File "/home/abhasker/.local/lib/python3.5/site-packages/gif_for_cli/__main__.py", line 84, in execute
    seconds_per_frame=config['seconds'] / config['num_frames']
ZeroDivisionError: float division by zero
```

**Comment by SeanHayes** [comment]
What version of ffmpeg are you running?

I suppose if we can't detect the right FPS, we could always assume 10 FPS, which is common for GIFs.

**Comment by Abhinickz** [comment]
Please find the ffmpeg version:

```
[01:44:25 abhasker@wsl -> ~$ ffmpeg  --version
ffmpeg version 2.8.14-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
```

**Comment by elijose55** [comment]
Can I work on this issue, or has it been fixed?

**Comment by Abhinickz** [comment]
It seems to be working with this version of `ffmpeg`.

```
[01:44:25 abhasker@wsl -> ~$ ffmpeg -version
ffmpeg version 4.1.4-1build2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9 (Ubuntu 9.2.1-4ubuntu1)
configuration: --prefix=/usr --extra-version=1build2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100
```

**Comment by soumitradev** [comment]
Either way, it should ideally work as expected no matter what version of ffmpeg you have.
I can work on this

**Comment by deeeelin** [comment]
I encountered the same problem with ffmpeg version 6 , and I fixed it by changing the assignments of "num_frames " and "seconds" in _ run_ffmpeg() under generate/_ _init_ _ .py to the below ones:

 ```
      num_frames = int(re.search(r'frame=\s*(\d+)', err).group(1))

      fps = float(re.search(r' (\S*) fps', err).group(1))

      seconds=num_frames / fps
```


It seems that the line ```re.search(r'time=(\d{2}):(\d{2}):(\d{2}).(\d{2})', err).groups()```  in the function didn't get the correct time value , re.search() returns all zeroes. So I just alternatively search for fps and convert it back to the duration time .
