### ISSUE TITLE
Can't use gif-for-cli (Float division by zero on execute.py)

### ISSUE THREAD

**Issue by larkkjj** [google/gif-for-cli#33]
archlinux :: ~/Projects/gif-for-cli ‹master*› » gif-for-cli          
Traceback (most recent call last):
  File "/home/lark/.local/bin/gif-for-cli", line 33, in <module>
    sys.exit(load_entry_point('gif-for-cli==1.1.2', 'console_scripts', 'gif-for-cli')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lark/.local/lib/python3.11/site-packages/gif_for_cli-1.1.2-py3.11.egg/gif_for_cli/__main__.py", line 23, in main
    execute(os.environ, sys.argv[1:], sys.stdout)
  File "/home/lark/.local/lib/python3.11/site-packages/gif_for_cli-1.1.2-py3.11.egg/gif_for_cli/execute.py", line 94, in execute
    seconds_per_frame=config['seconds'] / config['num_frames'],
                      ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero

**Comment by FrancoCorleone** [comment]
I have exactly the same problem, any workarounds?

**Comment by SASUPERNOVA** [comment]
@FrancoCorleone You could manually edit `gif_for_cli/generate/__init__.py` to add my fixes [Add missing "rows" option in _save_config](https://github.com/google/gif-for-cli/pull/34/commits/bc40735780b10454c5e4e4ec09052734efc47a51)  and [Add fallback regex method to _run_ffmpeg](https://github.com/SASUPERNOVA/gif-for-cli/commit/0d0ea0eae44bcca5c0003dd94de6dc4146967ba7). If you are on arch, the files should be in `~/.local/lib/python3.11/site-packages/gif_for_cli-1.1.2-py3.11.egg/`. If not, check the path in your error message.

Edit: If you don't feel like manually editing, you could also replace `gif_for_cli/generate/__init__.py` with the [one from my repo](https://github.com/SASUPERNOVA/gif-for-cli/blob/issue-33-pt2/gif_for_cli/generate/__init__.py).

**Comment by Cephir23** [comment]
Same issue here. 

[cephir@archlinux]$ gif-for-cli
Traceback (most recent call last):
  File "/home/cephir/.local/bin/gif-for-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cephir/.local/lib/python3.11/site-packages/gif_for_cli/__main__.py", line 23, in main
    execute(os.environ, sys.argv[1:], sys.stdout)
  File "/home/cephir/.local/lib/python3.11/site-packages/gif_for_cli/execute.py", line 94, in execute
    seconds_per_frame=config['seconds'] / config['num_frames'],
                      ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero


I tried replacing gif_for_cli/generate/__init__.py with the one from your repo, but it doesn't work for me.

**Comment by SASUPERNOVA** [comment]
@Cephir23 That may be because you have already used the bugged version of `gif-for-cli`. When gif-for-cli reads a GIF, it creates a cache directory for the image where it places a `config.json`, which contains `num_frames`. Once that config is created, it will remain the same on each execution, so `num_frames` should still be 0, causing a divide by zero error. On my system (probably yours as well since you use Arch), the cache directory is `~/.cache/gif-for-cli/1.1.2`. If there are any directories in the cache, try removing them and rerunning `gif-for-cli`.

**Comment by Cephir23** [comment]
> @Cephir23 That may be because you have already used the bugged version of `gif-for-cli`. When gif-for-cli reads a GIF, it creates a cache directory for the image where it places a `config.json`, which contains `num_frames`. Once that config is created, it will remain the same on each execution, so `num_frames` should still be 0, causing a divide by zero error. On my system (probably yours as well since you use Arch), the cache directory is `~/.cache/gif-for-cli/1.1.2`. If there are any directories in the cache, try removing them and rerunning `gif-for-cli`.

Worked! Thank you so much.

**Comment by Lepidos** [comment]
num_fames is on: gif_for_cli/generate/__init__.py

just replace it
-    num_frames = int(re.search(r'frame=\s*(\d+)', err).group(1))
+    num_frames = len(glob.glob1('{}/'.format(output_dirnames['jpg']),"*.jpg"))

https://github.com/Lepidos/gif-for-cli/blob/master/gif_for_cli/generate/__init__.py
